import { Direction, Faculty, Group, Speciality } from 'core/models/domain/university';
/**
 * Anecdotes API
 * Anecdotes API's
 *
 * OpenAPI spec version: 0.0.3
 * Contact: apiteam@anecdotes.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserId {
  uid?: string;
}
export interface User extends UserId {
  email?: string;
  role: RoleEnum;
  photoUrl?: string;
  firstName?: string;
  lastName?: string;
  password?: string;

  direction: Direction;
  faculty: Faculty;
  speciality?: Speciality;
  group?: Group;

  // room id's as array
  rooms: string[];
}

export type RoleEnum = 'student' | 'university staff';

export const RoleEnum = {
  Student: 'student' as RoleEnum,
  UniversityStaff: 'university staff' as RoleEnum,
};
